#!/bin/python3

import subprocess
from sys import argv

secret_tool_attribute = 'login'
secret_tool_value = 'ubuntu'

def read(cmd):
  child = subprocess.Popen(
    cmd,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT
  )
  return child.stdout.read()

def read_int(cmd) -> int:
  return int(read(cmd))

def max_brightness():
  return read_int(['cat', '/sys/class/backlight/intel_backlight/max_brightness'])

def cur_brightness():
  return read_int(['cat', '/sys/class/backlight/intel_backlight/actual_brightness'])

def pw():
  return read(['secret-tool', 'lookup', secret_tool_attribute, secret_tool_value])

def set_brightness(bNew):
  bMax = max_brightness()
  if bNew < 0:
    bNew = 0
  if bNew > bMax:
    bNew = bMax
  p = subprocess.Popen(
    [
      'sudo', '-S', 'sh', '-c',
      f'echo {bNew} | sudo tee /sys/class/backlight/intel_backlight/brightness'
    ],
    stdin=subprocess.PIPE
  )
  p.communicate(pw())

def brightness_down():
  bCur = cur_brightness()
  set_brightness(bCur - 10)

def brightness_up():
  bCur = cur_brightness()
  set_brightness(bCur + 50)

if len(argv) < 2:
  bMax = max_brightness()
  bCur = cur_brightness()
  print(f'Current brightness: {bCur}/{bMax}')
  print(f'')
  print(f'Usage:')
  print(f'  brightness down    - decrease brightness')
  print(f'  brightness up      - increase brightness')
  print(f'  brightness NUMBER  - set brightness to NUMBER')
  exit(1)

if argv[1] == 'down':
  brightness_down()
elif argv[1] == 'up':
  brightness_up()
else:
  set_brightness(int(argv[1]))
